# Generated by Django 5.1.7 on 2025-12-05 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_badhabit_badhabitlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="workoutexercise",
            name="reps_performed",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Actual number of reps done (for volume calc)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="workoutexercise",
            name="reps",
            field=models.CharField(
                blank=True, help_text="Target reps (e.g. '8-12')", max_length=50
            ),
        ),
    ]
