# Generated by Django 5.1.7 on 2025-12-08 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_workoutexercise_reps_performed_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="studysession",
            options={"ordering": ["-date", "-start_time"]},
        ),
        migrations.AddField(
            model_name="workouttype",
            name="targeted_muscles",
            field=models.ManyToManyField(
                blank=True, related_name="workout_types", to="core.muscle"
            ),
        ),
    ]
